version: "3"

services:
  app:
    image: node
    depends_on:
      - mongo
    build: .
    command: bash -c "npm install && npm run start:debug"
    ports:
      - 8080:8080
    volumes:
      - .:/home/node
      - /home/node/node_modules
    environment:
      - MONGO_DSN=mongodb://mongo:27017/phonebook

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017